// Package sinesync holds build-time release metadata that must live at the
// module root.
//
// It exists for one reason: go:embed cannot reference files outside the
// directory of the package that declares it, so a key file at the repository
// root cannot be embedded from internal/cli. This package sits next to the key
// and re-exports it.
package sinesync

import _ "embed"

// ReleaseEd25519PublicKey is the base64-encoded raw 32-byte Ed25519 public key
// that release signatures are verified against.
//
// A real key is committed and verification is LIVE: sinesync-release-ed25519.pub
// holds a usable 32-byte key, releasePublicKey in internal/cli/update.go returns
// it rather than errNoReleaseKey, and `sinesync update` verifies every release
// against it. Builds cut from this tree will refuse to install a release whose
// checksums.txt.sig does not verify under this exact key.
//
// The placeholder machinery it replaced is still in place and still load-bearing
// for the empty and PLACEHOLDER-prefixed cases — see placeholderKeyPrefix and
// errNoReleaseKey. If this file is ever emptied or reverted to a placeholder,
// clients stop installing updates entirely rather than installing unverified
// ones, and TestCommittedReleaseKeyIsReal in internal/cli/update_test.go fails
// so that happens on purpose rather than by accident.
//
// Provisioning, deliberately: the keypair was generated by a human outside any
// agent session; the private half was piped straight into the
// RELEASE_ED25519_PRIVATE_KEY GitHub Actions secret without touching disk, and
// only the public half is committed. A signing key is the root of trust for a
// binary that auto-executes on every user machine, so it must never exist in a
// scratchpad, a transcript, or any file an agent can read. Nothing in this
// repository can confirm the secret holds the matching private half, and nothing
// should be able to: that pairing is asserted at release time instead, by
// tools/signrelease, which is handed this file's path via --pubkey-file, derives
// the public key from the secret, and fails the release on any mismatch.
//
// This is deliberately separate from sinesync-release.pub, the ASCII-armored
// OpenPGP key that signs checksums.txt.asc for humans. The updater does not
// parse OpenPGP: a raw ed25519.Verify call has nothing subtle to get wrong,
// whereas x/crypto/openpgp is deprecated and frozen and a parsing bug there
// would mean forged signatures verify.
//
//go:embed sinesync-release-ed25519.pub
var ReleaseEd25519PublicKey string
