// Package sinesync holds build-time release metadata that must live at the
// module root.
//
// It exists for one reason: go:embed cannot reference files outside the
// directory of the package that declares it, so a key file at the repository
// root cannot be embedded from internal/cli. This package sits next to the key
// and re-exports it.
package sinesync

import _ "embed"

// ReleaseEd25519PublicKey is the base64-encoded raw 32-byte Ed25519 public key
// that release signatures are verified against.
//
// The committed file is currently a PLACEHOLDER, and a build carrying it
// refuses to install updates rather than skipping verification — see
// errNoReleaseKey in internal/cli/update.go. That is the intended state until
// the real key lands.
//
// Provisioning, deliberately: the keypair is generated by a human outside any
// agent session; the private half is piped straight into the
// RELEASE_ED25519_PRIVATE_KEY GitHub Actions secret without touching disk, and
// only the public half is committed. A signing key is the root of trust for a
// binary that auto-executes on every user machine, so it must never exist in a
// scratchpad, a transcript, or any file an agent can read.
//
// Replacing sinesync-release-ed25519.pub with the real public key is the ONLY
// client-side step required. The path is fixed and already matches what
// .github/workflows/release.yml handles, so nothing else moves when it lands.
//
// This is deliberately separate from sinesync-release.pub, the ASCII-armored
// OpenPGP key that signs checksums.txt.asc for humans. The updater does not
// parse OpenPGP: a raw ed25519.Verify call has nothing subtle to get wrong,
// whereas x/crypto/openpgp is deprecated and frozen and a parsing bug there
// would mean forged signatures verify.
//
//go:embed sinesync-release-ed25519.pub
var ReleaseEd25519PublicKey string
